import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/Navbar";

export const metadata: Metadata = {
  title: "Smaet Job AI",
  icons: "/favicon.png",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={` antialiased bg-white dark:bg-slate-900`}>
        <Navbar />

        <main className="max-w-7xl mx-auto ">
         {children}
        </main>
        <div className="h-screen"></div>
        <div className="h-screen"></div>
        <footer>this is footer</footer>
      </body>
    </html>
  );
}
