import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/Navbar";
import { getServerSession } from "next-auth";
import ReduxProvider from "@/lib/ReduxProvider";
import QueryProvider from "@/lib/QueryProvider";


export const metadata: Metadata = {
  title: "Smaet Job AI",
  icons: "/favicon.png",
  description: "Generated by create next app",
};



export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={` antialiased bg-white dark:bg-slate-900`}>
        <>
        <QueryProvider>

          <ReduxProvider>
            <Navbar session={session} />

            <main className=" ">{children}</main>
                

                <div className="h-screen">

                </div>
            <footer>this is footer</footer>
          </ReduxProvider>
        </QueryProvider>
        </>
      </body>
    </html>
  );
}
